### ISSUE TITLE
Media files available?

### ISSUE THREAD

**Issue by michaelmowry** [MarkHershey/Multimodal-NFT#1]
Great work on this. I am using it as part of a class I am taking on AI.  Is it possible to download the media files for this project? I noticed the json text data but didn't see the images, video, and audio files.

**Comment by MarkHershey** [comment]
https://github.com/MarkHershey/Multimodal-NFT/blob/9311f745f90a87a7e40274e75182661f7cb3ffd9/README.md?plain=1#L19

**Comment by michaelmowry** [comment]
Missed that, thank you
